package Model;
// Generated Jun 13, 2022 2:31:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Avaliacao generated by hbm2java
 */
public class Avaliacao  implements java.io.Serializable {


     private int codigo;
     private String descricao;
     private Set notarealizas = new HashSet(0);

    public Avaliacao() {
    }

	
    public Avaliacao(int codigo, String descricao) {
        this.codigo = codigo;
        this.descricao = descricao;
    }
    public Avaliacao(int codigo, String descricao, Set notarealizas) {
       this.codigo = codigo;
       this.descricao = descricao;
       this.notarealizas = notarealizas;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getNotarealizas() {
        return this.notarealizas;
    }
    
    public void setNotarealizas(Set notarealizas) {
        this.notarealizas = notarealizas;
    }




}


