package Model;
// Generated Jun 13, 2022 2:31:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estudante generated by hbm2java
 */
public class Estudante  implements java.io.Serializable {


     private int nrMatricula;
     private String nome;
     private String apelido;
     private String contacto;
     private String endereco;
     private Set notarealizas = new HashSet(0);

    public Estudante() {
    }

	
    public Estudante(int nrMatricula, String nome, String apelido) {
        this.nrMatricula = nrMatricula;
        this.nome = nome;
        this.apelido = apelido;
    }
    public Estudante(int nrMatricula, String nome, String apelido, String contacto, String endereco, Set notarealizas) {
       this.nrMatricula = nrMatricula;
       this.nome = nome;
       this.apelido = apelido;
       this.contacto = contacto;
       this.endereco = endereco;
       this.notarealizas = notarealizas;
    }
   
    public int getNrMatricula() {
        return this.nrMatricula;
    }
    
    public void setNrMatricula(int nrMatricula) {
        this.nrMatricula = nrMatricula;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Set getNotarealizas() {
        return this.notarealizas;
    }
    
    public void setNotarealizas(Set notarealizas) {
        this.notarealizas = notarealizas;
    }




}


