package Model;
// Generated Jun 13, 2022 2:31:50 PM by Hibernate Tools 3.6.0



/**
 * Notarealiza generated by hbm2java
 */
public class Notarealiza  implements java.io.Serializable {


     private int codigo;
     private Disciplina disciplina;
     private Avaliacao avaliacao;
     private Estudante estudante;
     private double nota;

    public Notarealiza() {
    }

    public Notarealiza(int codigo, Disciplina disciplina, Avaliacao avaliacao, Estudante estudante, double nota) {
       this.codigo = codigo;
       this.disciplina = disciplina;
       this.avaliacao = avaliacao;
       this.estudante = estudante;
       this.nota = nota;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }
    public Avaliacao getAvaliacao() {
        return this.avaliacao;
    }
    
    public void setAvaliacao(Avaliacao avaliacao) {
        this.avaliacao = avaliacao;
    }
    public Estudante getEstudante() {
        return this.estudante;
    }
    
    public void setEstudante(Estudante estudante) {
        this.estudante = estudante;
    }
    public double getNota() {
        return this.nota;
    }
    
    public void setNota(double nota) {
        this.nota = nota;
    }




}


