package Model;
// Generated Jun 13, 2022 2:31:50 PM by Hibernate Tools 3.6.0



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String pass;
     private String email;
     private String teleofne;

    public Users() {
    }

    public Users(String username, String pass, String email, String teleofne) {
       this.username = username;
       this.pass = pass;
       this.email = email;
       this.teleofne = teleofne;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTeleofne() {
        return this.teleofne;
    }
    
    public void setTeleofne(String teleofne) {
        this.teleofne = teleofne;
    }




}


